
package dsd.cms.wsdlclasses;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DCMSInterface", targetNamespace = "http://interfaces.cms.dsd/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DCMSInterface {


    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "editRecord", targetNamespace = "http://interfaces.cms.dsd/", className = "dsd.cms.interfaces.EditRecord")
    @ResponseWrapper(localName = "editRecordResponse", targetNamespace = "http://interfaces.cms.dsd/", className = "dsd.cms.interfaces.EditRecordResponse")
    @Action(input = "http://interfaces.cms.dsd/DCMSInterface/editRecordRequest", output = "http://interfaces.cms.dsd/DCMSInterface/editRecordResponse", fault = {
        @FaultAction(className = IOException.class, value = "http://interfaces.cms.dsd/DCMSInterface/editRecord/Fault/IOException")
    })
    public String editRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3)
        throws IOException
    ;

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transferRecord", targetNamespace = "http://interfaces.cms.dsd/", className = "dsd.cms.interfaces.TransferRecord")
    @ResponseWrapper(localName = "transferRecordResponse", targetNamespace = "http://interfaces.cms.dsd/", className = "dsd.cms.interfaces.TransferRecordResponse")
    @Action(input = "http://interfaces.cms.dsd/DCMSInterface/transferRecordRequest", output = "http://interfaces.cms.dsd/DCMSInterface/transferRecordResponse", fault = {
        @FaultAction(className = IOException.class, value = "http://interfaces.cms.dsd/DCMSInterface/transferRecord/Fault/IOException")
    })
    public String transferRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2)
        throws IOException
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @param arg8
     * @return
     *     returns java.lang.String
     * @throws IOException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createTRecord", targetNamespace = "http://interfaces.cms.dsd/", className = "dsd.cms.interfaces.CreateTRecord")
    @ResponseWrapper(localName = "createTRecordResponse", targetNamespace = "http://interfaces.cms.dsd/", className = "dsd.cms.interfaces.CreateTRecordResponse")
    @Action(input = "http://interfaces.cms.dsd/DCMSInterface/createTRecordRequest", output = "http://interfaces.cms.dsd/DCMSInterface/createTRecordResponse", fault = {
        @FaultAction(className = IOException.class, value = "http://interfaces.cms.dsd/DCMSInterface/createTRecord/Fault/IOException")
    })
    public String createTRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        String arg7,
        @WebParam(name = "arg8", targetNamespace = "")
        boolean arg8)
        throws IOException
    ;

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg5
     * @param arg4
     * @param arg1
     * @param arg0
     * @param arg7
     * @param arg6
     * @return
     *     returns java.lang.String
     * @throws IOException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createSRecord", targetNamespace = "http://interfaces.cms.dsd/", className = "dsd.cms.interfaces.CreateSRecord")
    @ResponseWrapper(localName = "createSRecordResponse", targetNamespace = "http://interfaces.cms.dsd/", className = "dsd.cms.interfaces.CreateSRecordResponse")
    @Action(input = "http://interfaces.cms.dsd/DCMSInterface/createSRecordRequest", output = "http://interfaces.cms.dsd/DCMSInterface/createSRecordResponse", fault = {
        @FaultAction(className = IOException.class, value = "http://interfaces.cms.dsd/DCMSInterface/createSRecord/Fault/IOException")
    })
    public String createSRecord(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3,
        @WebParam(name = "arg4", targetNamespace = "")
        String arg4,
        @WebParam(name = "arg5", targetNamespace = "")
        String arg5,
        @WebParam(name = "arg6", targetNamespace = "")
        String arg6,
        @WebParam(name = "arg7", targetNamespace = "")
        boolean arg7)
        throws IOException
    ;

    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listRecordID", targetNamespace = "http://interfaces.cms.dsd/", className = "dsd.cms.interfaces.ListRecordID")
    @ResponseWrapper(localName = "listRecordIDResponse", targetNamespace = "http://interfaces.cms.dsd/", className = "dsd.cms.interfaces.ListRecordIDResponse")
    @Action(input = "http://interfaces.cms.dsd/DCMSInterface/listRecordIDRequest", output = "http://interfaces.cms.dsd/DCMSInterface/listRecordIDResponse")
    public List<String> listRecordID();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     * @throws IOException
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getRecordCounts", targetNamespace = "http://interfaces.cms.dsd/", className = "dsd.cms.interfaces.GetRecordCounts")
    @ResponseWrapper(localName = "getRecordCountsResponse", targetNamespace = "http://interfaces.cms.dsd/", className = "dsd.cms.interfaces.GetRecordCountsResponse")
    @Action(input = "http://interfaces.cms.dsd/DCMSInterface/getRecordCountsRequest", output = "http://interfaces.cms.dsd/DCMSInterface/getRecordCountsResponse", fault = {
        @FaultAction(className = IOException.class, value = "http://interfaces.cms.dsd/DCMSInterface/getRecordCounts/Fault/IOException")
    })
    public String getRecordCounts(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0)
        throws IOException
    ;

}
