
package dsd.cms.wsdlclasses;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DollardServerService", targetNamespace = "http://server.cms.dsd/", wsdlLocation = "http://localhost:8080/DCMS/DDO?wsdl")
public class DollardServerService
    extends Service
{

    private final static URL DOLLARDSERVERSERVICE_WSDL_LOCATION;
    private final static WebServiceException DOLLARDSERVERSERVICE_EXCEPTION;
    private final static QName DOLLARDSERVERSERVICE_QNAME = new QName("http://server.cms.dsd/", "DollardServerService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/DCMS/DDO?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DOLLARDSERVERSERVICE_WSDL_LOCATION = url;
        DOLLARDSERVERSERVICE_EXCEPTION = e;
    }

    public DollardServerService() {
        super(__getWsdlLocation(), DOLLARDSERVERSERVICE_QNAME);
    }

    public DollardServerService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DOLLARDSERVERSERVICE_QNAME, features);
    }

    public DollardServerService(URL wsdlLocation) {
        super(wsdlLocation, DOLLARDSERVERSERVICE_QNAME);
    }

    public DollardServerService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DOLLARDSERVERSERVICE_QNAME, features);
    }

    public DollardServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DollardServerService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DCMSInterface
     */
    @WebEndpoint(name = "DollardServerPort")
    public DCMSInterface getDollardServerPort() {
        return super.getPort(new QName("http://server.cms.dsd/", "DollardServerPort"), DCMSInterface.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DCMSInterface
     */
    @WebEndpoint(name = "DollardServerPort")
    public DCMSInterface getDollardServerPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://server.cms.dsd/", "DollardServerPort"), DCMSInterface.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DOLLARDSERVERSERVICE_EXCEPTION!= null) {
            throw DOLLARDSERVERSERVICE_EXCEPTION;
        }
        return DOLLARDSERVERSERVICE_WSDL_LOCATION;
    }

}
